name = "speedylabs-dashboard"
main = "dist/worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"
watch_dir = "src"

[env.production]
workers_dev = false
routes = [
  { pattern = "speedylabs.pages.dev/*", zone_name = "speedylabs.pages.dev" }
]

[env.staging]
workers_dev = true
name = "speedylabs-dashboard-staging" 